### ISSUE TITLE
about predict rhythmic values

### ISSUE THREAD

**Issue by Wenhui-bio** [RWParsons/circacompare#5]
Hi, Rex @RWParsons 
Sorry, I have another question now. Can we predict the rhythmic expression level in any time of a day from fitted model? I'am not sure  the code shown below whether correct or not.
```
# fit model
data_single <- make_data(k1=0, alpha1=0, phi1=0, noise_sd=1)[c("time", "measure")][1:48,]
result <- circa_single(x=data_single, col_time="time", col_outcome="measure", period=24)
# predict
dt <- data.frame(time=seq(1,48, length.out=1000))
result.new <- predict(result$fit, newdata=dt)
## the result in 'result.new' only have 48 values, why cann't be predicted to produce 1000 values within 48h.
```
I want to check rhythmic expression value at certain time point, at which the expression levels didn't measure. So can we predict that value from fitted model?
Thanks!

**Comment by RWParsons** [comment]
Hi Whui,

Good question! If I were making circacompare again, I would implement a predict method to make this work as you expect. 
In the meantime, you can achieve the same thing by replicating the transformation that circacompare does before it fits the model. In the model, the period is included so you have to add this as a column. And you also have to create a time_r column which is the time * 2 * pi. Here's what I've done to modify your example.

```
library(circacompare)

data_single <- make_data(k1=0, alpha1=0, phi1=0, noise_sd=1)[c("time", "measure")][1:48,]
result <- circa_single(x=data_single, col_time="time", col_outcome="measure", period=24)
# predict
dt <- data.frame(time=seq(1,48, length.out=1000))

dt$time_r <- dt$time * 2 * pi
dt$period <- 24
dt$result.new <- predict(result$fit, newdata=dt)

plot(dt$time, dt$result.new)
```

I'd like to update circacompare to work a bit nicer and behave as you'd expect here. Hopefully sometime in the future but at this stage I'm not prepared to make all the breaking changes to recreate the package using S3. (Maybe in the future...) So I'll close this issue with the solution that I've given above.

Thanks,
Rex

**Comment by Wenhui-bio** [comment]
Thank you very much.
