### ISSUE TITLE
Support per-sample weights

### ISSUE THREAD

**Issue by ATpoint** [RWParsons/circacompare#7]
Dear Rex,

I would like to follow up on (https://github.com/RWParsons/circacompare/issues/3) towards support of per-sample weights. Did you happen to have any time supporting this for `circacompare()`? I tried naive solutions by providing a numeric vector of weights to `nls()` as an [argument](https://github.com/ATpoint/circacompare/blob/master/R/circacompare.R#L159) -- turns out it is more complex than that... 

Do you currently have the capacity to help out here, or alternatively, can you point me to the sections in the source code that I need to dig myself into to address this?

Thank you very much!
-Alex

**Comment by RWParsons** [comment]
Hi Alex,

I forgot why I said it was hard before in the other issue but I think you'd need to add an argument to circacompare for the weights vector and then pass it to the call to `stats::nls()` [here](https://github.com/RWParsons/circacompare/blob/effd92ef6beb4bf6558ad2ae1177e95e6d9a34a3/R/circacompare.R#L149).

I'm busy for the next week or two but may have time to have another look at this after that. I'll keep it open but please give me an update on how you go over the next week or two before I have a go.

Thanks,
Rex

**Comment by ATpoint** [comment]
Hi Rex,

thank you for the response!

I think I managed now in https://github.com/ATpoint/circacompare/commit/0ceb788e0338db4dbe75e3cbbc6c22ffcb3db8c8

The tricky part was to realize that the `nls()` function creates its own local environment so one first has to add the weights to the `x` input data.frame which then allows to use the `weights` argument in `nls`, see [here](https://github.com/ATpoint/circacompare/blob/master/R/circacompare.R#L155) and [here](https://github.com/ATpoint/circacompare/blob/master/R/circacompare.R#L169). If you provide the weights directly to `nls()` without adding to `x` first then you get an error as [here at SO](https://stackoverflow.com/questions/61164404/call-to-weight-in-lm-within-function-doesnt-evaluate-properly). 

Limitation: I only added this to the `nls()` that runs the differential analysis, not to the `model_each_group()` function which assesses rhythmicity per group. For my specific use-case that's fine, so I will work with the forked version for now. Will close the issue for now. Happy to make a PR at some point if you find this generally reliable. Cheers!

Edit: Will make a PR with the points you mention below once I find the time, thanks!

**Comment by RWParsons** [comment]
Thanks Alex,

Looks like this is a good fix that I'm sure would be helpful to others too. I'm happy to merge this in and add you as a contributor. Before you do a pull request, could you please add the sample_weights arg and functionality to the other circacompare functions (*_single and the *_mixed variants)?

**Comment by ATpoint** [comment]
All done in https://github.com/RWParsons/circacompare/pull/8 :)
